DEBUG = True

SQLALCHEMY_DATABASE_URI = 'mysql://tourvi45_aps:unip@2020@50.116.112.31:3306/tourvi45_APS'

SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = 'CHAVEDAORA'

UPLOAD_FOLDER = 'Images'
EXPLAIN_TEMPLATE_LOADING = True