"""empty message

Revision ID: 3070b599c7fe
Revises: c3d96dcf8d40
Create Date: 2020-09-21 22:02:23.665827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3070b599c7fe'
down_revision = 'c3d96dcf8d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nivelAcesso', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nivelAcesso')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
